#!/usr/bin/env ruby

def process(llp)
  unpack_output = `jruby -S limelight unpack #{llp}`
  production_path = unpack_output.split(":")[1].strip
  
  require 'playbill'
  name = File.basename(llp).gsub(".llp", "")
  info = load_info(production_path)
  info[:name] = name
  info[:size] = File.size(llp).to_s
  
  playbill = Playbill.find_by_name(name)
  if playbill
    playbill.update_attributes(info)
  else
    playbill = Playbill.create(info) 
  end
  
  playbill.establish_data_dir
  save_llp(playbill, llp)
  save_thumbnail(playbill, production_path)
end

def load_info(production_path)
  info_path = File.join(production_path, "__resources", "info.yaml")
  if File.exist?(info_path)
    require 'yaml'
    info = YAML.load(IO.read(info_path))
    return info
  end
  return {}
end

def save_llp(playbill, llp)
  system "cp #{llp} #{playbill.llp_file}"
end

def save_thumbnail(playbill, production_path)
  thumbnail_path = File.join(production_path, "__resources", "thumbnail.png")
  if File.exist?(thumbnail_path)
    system "cp #{thumbnail_path} #{playbill.thumbnail_file}"
  end
end

llp_name = ARGV[0]
raise "Please provide the path to a .llp file." if llp_name.nil? || !File.exist?(llp_name)
require File.expand_path(File.dirname(__FILE__) + "/../config/environment.rb")
process(llp_name)



